server:
  port: ${PORT:9092}
  servlet:
    context-path: /

oauth2-config:
  client-id: ${CLIENT_ID:76179baad962d1b8ce4d}
  client-secret: ${CLIENT_SECRET:8faedc0e6e1520d13f06f787d6760c303f3e8768}
  server-url: ${OAUTH2_URL:https://development-oauth-server.herokuapp.com}

spring:
    datasource:
        url: jdbc:postgresql://ec2-18-213-176-229.compute-1.amazonaws.com:5432/dd6k204tvumd0g
        username: ehncqxkufegxkv
        password: a1759be25c60f8d389c8943adf8dbdb9cb4b04e19ef7536f2be8f3da276bf3b6
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: validate
        show-sql: ${HIBERNATE_SHOW_SQL:false}
        properties:
            hibernate:
                generate_statistics: ${HIBERNATE_STATISTICS:false}
                temp:
                    use_jdbc_metadata_defaults: false

security:
  oauth2:
    client:
      clientId: ${oauth2-config.client-id}
      clientSecret: ${oauth2-config.client-secret}
      accessTokenUri: ${oauth2-config.server-url}/oauth/token
      userAuthorizationUri: ${oauth2-config.server-url}/oauth/authorize

    resource:
      userInfoUri: ${oauth2-config.server-url}/user/info
      tokenInfoUri: ${oauth2-config.server-url}/oauth/check_token

salesforce:
  instance:
    apiVersion: ${SALESFORCE_API_VERSION:v48.0}
    instanceId: ${SALESFORCE_INSTANCE_ID}

  oauth2:
    clientId: ${SALESFORCE_CLIENT_ID}
    clientSecret: ${SALESFORCE_CLIENT_SECRET}
    username: ${SALESFORCE_USERNAME}
    password: ${SALESFORCE_PASSWORD}
  
  keystore:
    path: ${KEYSTORE_PATH:classpath:keystore/keystore.jks}
    password: ${KEYSTORE_PASSWORD:ottimizza@123}

